// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginReply struct {
	Id           int64  `json:"id"`
	Name         string `json:"name"`
	Gender       string `json:"gender"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type UserReq struct {
	UserId int64 `json:"userid"`
}

type UserReply struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Gender string `json:"gender"`
}

type UserUpdateReq struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Password string `json:"password"`
	Gender   string `json:"gender"`
}

type UserUpdateReply struct {
	ResCode string `json:"rescode"`
	ResDesc string `json:"resdesc"`
}

type UserSaveReq struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Gender   string `json:"gender"`
}

type UserSaveReply struct {
	ResCode string `json:"rescode"`
	ResDesc string `json:"resdesc"`
}

type UserDeleteReq struct {
	Id int64 `json:"id"`
}

type UserDeleteReply struct {
	ResCode string `json:"rescode"`
	ResDesc string `json:"resdesc"`
}
