// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"private/services/users/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: loginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/saveuser",
				Handler: saveuserHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/getusers",
				Handler: getusersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/getuser",
				Handler: getuserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/updateuser",
				Handler: updateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/user/deleteuser",
				Handler: deleteUserHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/ping",
				Handler: pingHandler(serverCtx),
			},
		},
	)
}
